services:
  - type: web
    name: csv-to-json-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: csv-converter-db
          property: connectionString

databases:
  - name: csv-converter-db
    databaseName: csv_converter
    user: csv_user